# Generated by Django 5.2a1 on 2025-02-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balances', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming'), ('transfer', 'Transfer')], max_length=10)),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='balances.balance')),
                ('balance_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='balances.balance')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
