# Generated by Django 5.1.6 on 2025-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeoutcometransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], default='outcome', max_length=10),
        ),
    ]
