# Generated by Django 5.1.6 on 2025-02-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_alter_incomeoutcometransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetransaction',
            name='date',
            field=models.DateField(),
        ),
    ]
