# Generated by Django 5.1.6 on 2025-02-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
        ('transactions', '0002_alter_transaction_currency_historicaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='balances.balance'),
        ),
    ]
