# Generated by Django 5.1.6 on 2025-02-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name_alter_category_unique_together'),
        ('transactions', '0003_alter_basetransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetransaction',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category'),
        ),
    ]
