# Generated by Django 5.1.6 on 2025-02-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_basetransaction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basetransaction',
            old_name='name',
            new_name='category',
        ),
    ]
