# Generated by Django 5.1.6 on 2025-03-26 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_name_basetransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetransaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basetransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
